const data = {
  brand: {
    name: "Kalavishva",
    tagline: "crafted with soul",
    logo: "/products/logo.jpg",
    email: "kalavishvacraftedwithsoul@gmail.com",
    phone: "9762324854",
    whatsapp: "919762324854",
    currency: "₹",
    location: "India",
  },

  navigation: [
    { name: "Home", link: "#home" },
    { name: "Shop", link: "#shop" },
    { name: "About", link: "#about" },
    { name: "Contact", link: "#contact" },
  ],

  announcement: {
    enabled: true,
    text: "Handcrafted with love • Made with soul • Made in India",
  },

  hero: {
    enabled: true,
    autoplay: true,
    interval: 4500,
    slides: [
      {
        image: "/products/hero-1.png",
        title: "Crafted With Soul",
        subtitle: "Beautiful handmade creations made with love, care and imagination.",
        buttonText: "Explore Collection",
        buttonLink: "#shop",
      },
      {
        image: "/products/hero-2.jpg",
        title: "Art That Tells A Story",
        subtitle: "Discover unique creations that bring warmth and character to your space.",
        buttonText: "Shop Now",
        buttonLink: "#shop",
      },
      {
        image: "/products/hero-3.jpg",
        title: "Made For Meaningful Moments",
        subtitle: "Thoughtfully crafted pieces for gifting, decorating and celebrating.",
        buttonText: "View Products",
        buttonLink: "#shop",
      },
      {
        image: "/products/hero-4.png",
        title: "Handmade. Unique. Yours.",
        subtitle: "Every piece carries the warmth of human hands and a little piece of soul.",
        buttonText: "Discover More",
        buttonLink: "#shop",
      },
    ],
  },

  story: {
    enabled: true,
    smallTitle: "THE KALAVISHVA STORY",
    title: "Crafted with soul, made to be cherished.",
    description:
      "At Kalavishva, we believe beautiful things carry a piece of the person who creates them. Every creation is thoughtfully designed and carefully crafted to bring warmth, beauty and meaning into everyday life.",
    buttonText: "Explore Our Collection",
    buttonLink: "#shop",
    image: "/products/story.jpg",
  },

  categories: ["All", "Home Decor", "Handmade", "Gifting", "Art"],

  products: [
    // {
    //   id: 1,
    //   name: "Vadani Kaval ( वदनी कवळ )",
    //   category: "Fridge Magnet",
    //   price: 50,
    //   oldPrice: 99,
    //   image: "/products/product1.png",
    //   description: "A sacred daily meal prayer brought to life on your kitchen fridge.",
    //   available: true,
    //   featured: true,
    // },
{
  id: 1,
  name: "Vadani Kaval (वदनी कवळ)",
  category: "Fridge Magnet",

  price: 50,
  oldPrice: 100,

  sale: true,
  saleLabel: "50 % OFF",

  image: "/products/product1.png",

  description: "A sacred daily meal prayer brought to life on your kitchen fridge.(4*3 Inch)",

  available: true,
  featured: true,
},

    {
      id: 2,
      name: "Marathi Calendar",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
      sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product2.png",
      description: "Celebrate every day with divine Marathi traditions on your fridge.(4*4 Inch)",
      available: true,
      featured: true,
    },
    {
      id: 3,
      name: "Namaste Sharde Devi",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product3.png",
      description: "A unique handcrafted art piece created to make your space feel personal.( 4*3 Inch)",
      available: true,
      featured: true,
    },
    {
      id: 4,
      name: "Gayatri Mantra",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product4.png",
      description: "A sacred symbol of divine wisdom, peace, and spiritual enlightenment.(4*4 Inch)",
      available: true,
      featured: true,
    },
    {
      id: 5,
      name: "Nishank Hoi re Mana",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product5.png",
      description: "A thoughtfully curated handmade gift set for someone special.",
      available: true,
      featured: true,
    },
    {
      id: 6,
      name: "Annapurna Leaf Fridge Magnet",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product6.png",
      description: "A charming miniature handmade piece perfect for gifting or decorating.",
      available: true,
      featured: false,
    },
    {
      id: 31,
      name: "Heritage Hand-Grind Marathi Traditional Fridge Magnet",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product31.png",
      description: "Bring home the warm nostalgia of traditional Maharashtrian heritage with this handcrafted magnet featuring classic Marathi Ovi verses and rural art.",
      available: true,
      featured: false,
    },
    {
      id: 32,
      name: "Radha Krishna Haldi Kumkum Set of 10",
      category: "Radha Krishna Haldi Kumkum Set of 10, Festive Return Gift",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product32.png",
      description: "Bring home the warm nostalgia of traditional Maharashtrian heritage with this handcrafted magnet featuring classic Marathi Ovi verses and rural art.",
      available: true,
      featured: false,
    },
    {
      id: 7,
      name: "Goddess Saraswati Symbol Slate",
      category: "Fridge Magnet",
      price: 70,
      oldPrice: 140,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product7.png",
      description: "Handcrafted Goddess Saraswati symbol on pure Khan cloth—blessing your space with wisdom and artistry.",
      available: true,
      featured: false,
    },
    {
      id: 8,
      name: "Goddess Saraswati Symbol (Square Khann)",
      category: "Fridge Magnet",
      price: 70,
      oldPrice: 140,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product8.png",
      description: "Handcrafted Goddess Saraswati symbol on pure Khan cloth—blessing your space with wisdom and artistry.",
      available: true,
      featured: false,
    },
    {
      id: 9,
      name: "Goddess Saraswati Symbol Round",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product9.png",
      description: "Goddess Saraswati symbol fridge magnet round MDF for decore and gifting.",
      available: true,
      featured: true,
    },
    {
      id: 10,
      name: "Shree Swami Samarth Home design",
      category: "Fridge Magnet",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product10.png",
      description: "Beautiful handcrafted wall art designed to add warmth and character to your home.",
      available: true,
      featured: true,
    },
    {
      id: 11,
      name: "Kathakali Fridge Magnet (Combo Offer)",
      category: "Home Decor",
      price: 80,
      oldPrice: 160,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product11.png",
      description: " A vibrant handcrafted Kathakali fridge magnet bringing the rich drama and classic art of Kerala to your kitchen.",
      available: true,
      featured: true,
    },
    {
      id: 12,
      name: "Namo Buddhay Fridge Magnet",
      category: "Home Decor",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product12.png",
      description: "A serene Buddha magnet with नमो बुद्धाय script to bring peace, mindfulness, and calm to your space.",
      available: true,
      featured: true,
    },
    {
      id: 13,
      name: "Krishnay Vaudevay Mantra Fridge Magnet",
      category: "Home Decor",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product13.png",
      description: " Lord Krishna mantra fridge magnet",
      available: true,
      featured: true,
    },
    {
      id: 14,
      name: "Aai Ambabai Fridge Magnet",
      category: "Home Decor",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product14.png",
      description: " Bring divine grace and blessings into your home with this beautifully detailed Aai Ambabai fridge magnet.",
      available: true,
      featured: true,
    },
    {
      id: 15,
      name: "Pichwai Art Print (Round 6 Inch)",
      category: "Home Decor",
      price: 60,
      oldPrice: 120,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product15.png",
      description: "Pichwai Kamdhenu Cow artwork—perfect as a table rangoli, wall accent, decorative piece, or a thoughtful gift.",
      available: true,
      featured: true,
    },
    {
      id: 16,
      name: "Shubh-Labh Laxmi devi and Saraswati Symbol Combo",
      category: "Home Decor",
      price: 110,
      oldPrice: 220,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product16.png",
      description: "Divine Shubh-Labh Lakshmi and Saraswati symbol fridge magnet set bringing wealth, wisdom, and auspicious energy to your home.",
      available: true,
      featured: true,
    },
    {
      id: 17,
      name: "Chaitrangan & Annapurna Leaf fridge magnet Combo",
      category: "Home Decor",
      price: 110,
      oldPrice: 220,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product17.png",
      description: "Sacred Chaitrangan and Annapurna leaf fridge magnet set bringing traditional rangoli blessings and food abundance to your kitchen.",
      available: true,
      featured: true,
    },
    {
      id: 18,
      name: "Devi Amababai Zarokha fridge Magnet (Pink/Redish)",
      category: "Home Decor",
      price: 160,
      oldPrice: 320,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product18.png",
      description: "Exquisite Devi Ambabai Jharokha fridge magnet bringing divine Kolhapuri blessings and traditional royal arch design to your space.",
      available: true,
      featured: true,
    },
    {
      id: 19,
      name: "Devi Amababai Zarokha fridge Magnet (Purple 6*4inch approx)",
      category: "Home Decor",
      price: 160,
      oldPrice: 320,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product19.png",
      description: "Exquisite Devi Ambabai Jharokha fridge magnet bringing divine Kolhapuri blessings and traditional royal arch design to your space.",
      available: true,
      featured: true,
    },
    {
      id: 20,
      name: "Devi Amababai Zarokha fridge Magnet (Green 6*4inch approx)",
      category: "Home Decor",
      price: 160,
      oldPrice: 320,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product20.png",
      description: "Exquisite Devi Ambabai Jharokha fridge magnet bringing divine Kolhapuri blessings and traditional royal arch design to your space.",
      available: true,
      featured: true,
    },
    {
      id: 21,
      name: "Devi Saraswati Zarokha fridge Magnet (Orange 6*4inch approx)",
      category: "Home Decor",
      price: 160,
      oldPrice: 320,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product21.png",
      description: "Brighten your fridge with this vibrant orange Devi Saraswati Jharokha magnet, bringing divine elegance and traditional craftsmanship to your home.",
      available: true,
      featured: true,
    },
    {
      id: 22,
      name: "Shree Swami Samarth Zarokha fridge Magnet (6*4inch approx)",
      category: "Home Decor",
      price: 160,
      oldPrice: 320,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product22.png",
      description: "Bring divine blessings and spiritual harmony into your home with this handcrafted Shree Swami Samarth Jharokha fridge magnet.",
      available: true,
      featured: true,
    },
    {
      id: 23,
      name: "Labhale amhas bhagya Fridge Magnet",
      category: "Home Decor",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product23.png",
      description: "Celebrate your love for the language with this handcrafted Labhale Amhas Bhagya Marathi fridge magnet, adding cultural pride to your home.",
      available: true,
      featured: true,
    },
    {
      id: 24,
      name: "Rajmudra Fridge Magnet ( 2.5 inch )",
      category: "Home Decor",
      price: 60,
      oldPrice: 120,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product24.png",
      description: "Honor the legacy of Chhatrapati Shivaji Maharaj with this 2.5-inch Shiv Rajmudra fridge magnet, adding royal Marathi heritage to your home.",
      available: true,
      featured: true,
    },
    {
      id: 25,
      name: "Maharashtra desha fridge magnet",
      category: "Home Decor",
      price: 50,
      oldPrice: 100,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product25.png",
      description: "Showcase your cultural pride with this handcrafted Maharashtra Desha fridge magnet, bringing the rich history and spirit of Maharashtra to your home.",
      available: true,
      featured: true,
    },
    {
      id: 26,
      name: "Subh Labh Wall Hanging",
      category: "Home Decor",
      price: 120,
      oldPrice: 240,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product26.png",
      description: "Bring a touch of positivity and traditional charm to your home with this Shubh Labh Wall Hanging.",
      available: true,
      featured: true,
    },
    {
      id: 27,
      name: "Peacock pair Wall Hanging",
      category: "Home Decor",
      price: 99,
      oldPrice: 198,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product27.png",
      description: "Bring a touch of positivity and traditional charm to your home with this peacock Wall Hanging.",
      available: true,
      featured: true,
    },
    {
      id: 28,
      name: "Diwali Combo Set",
      category: "Home Decor",
      price: 199,
      oldPrice: 398,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product28.png",
      description: "Combo of Subh Labh wall hanging and T light holder set",
      available: true,
      featured: true,
    },
    {
      id: 29,
      name: "velvet t-light candle holder (Set of 2)",
      category: "Home Decor",
      price: 249,
      oldPrice: 498,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product29.png",
      description: "Beautiful velvet t-light candle holders that add an attractive and elegant touch to your home décor",
      available: true,
      featured: true,
    },
     {
      id: 30,
      name: "T light candle holder with subh labh (Any 1)",
      category: "Home Decor",
      price: 99,
      oldPrice: 198,
        sale: true,
  saleLabel: "50 % OFF",
      image: "/products/product30.jpg",
      description: "Beautiful velvet t-light candle holders that add an attractive and elegant touch to your home décor",
      available: true,
      featured: true,
    },
  ],

   googleForm: {
    enabled: true,
     formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSetabdQDkNO1Z0It2PzeY_Sp9wSkDH16PJOqSyGVGt3Y3qcNw/viewform?usp=publish-editor",
    fields: {
      customerName: "entry.1111111111",
      phone: "entry.2222222222",
      address: "entry.3333333333",
      orderDetails: "entry.4444444444",
      totalAmount: "entry.5555555555",
    },
    submitButtonText: "Continue to Order Form",
  },

  whatsapp: {
    enabled: true,
    message: "Hello Kalavishva, I would like to know more about your products.",
    buttonText: "Chat on WhatsApp",
  },

  about: {
    title: "Made with heart. Crafted with soul.",
    description:
      "Kalavishva is a handmade brand created for people who appreciate beautiful things made with patience, creativity and love. Our creations are made to feel personal, meaningful and timeless.",
    points: [
      "Thoughtfully handcrafted",
      "Unique designs",
      "Made with care",
      "Perfect for gifting",
    ],
  },

  footer: {
    description:
      "Kalavishva creates soulful handmade products that bring beauty, warmth and meaning into everyday life.",
    copyright: "© 2026 Kalavishva. All rights reserved.",
  },
};

export default data;